In [6]:
import pandas as pd

In [7]:
# Load Data
house_data=pd.read_csv("HousePricePrediction.csv")

In [3]:
house_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [8]:
house_data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [9]:
house_data.shape

(2919, 13)

In [11]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [12]:
house_data.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [15]:
house_data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [31]:
# Data Preprocessing-Data cleaning


#drop Id as it doesn't contribute in price
#house_data.drop(['Id'],axis=1,inplace=True)

#replacing sales price empty values with their mean
house_data["SalePrice"]=house_data["SalePrice"].fillna(house_data["SalePrice"].mean())
house_data=house_data.dropna()
house_data.isnull().sum()
house_data.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [27]:

house_data

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [33]:
# Data Preprocessing -Encoding
cols=['MSZoning','LotConfig','BldgType','Exterior1st']
house_data=pd.get_dummies(house_data,columns=cols,drop_first=True)

In [37]:
house_data.columns

Index(['MSSubClass', 'LotArea', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'BsmtFinSF2', 'TotalBsmtSF', 'SalePrice', 'MSZoning_FV', 'MSZoning_RH',
       'MSZoning_RL', 'MSZoning_RM', 'LotConfig_CulDSac', 'LotConfig_FR2',
       'LotConfig_FR3', 'LotConfig_Inside', 'BldgType_2fmCon',
       'BldgType_Duplex', 'BldgType_Twnhs', 'BldgType_TwnhsE',
       'Exterior1st_AsphShn', 'Exterior1st_BrkComm', 'Exterior1st_BrkFace',
       'Exterior1st_CBlock', 'Exterior1st_CemntBd', 'Exterior1st_HdBoard',
       'Exterior1st_ImStucc', 'Exterior1st_MetalSd', 'Exterior1st_Plywood',
       'Exterior1st_Stone', 'Exterior1st_Stucco', 'Exterior1st_VinylSd',
       'Exterior1st_Wd Sdng', 'Exterior1st_WdShing'],
      dtype='object')

In [42]:
# Train-Test Split
from sklearn.model_selection import train_test_split
X=house_data.drop(['SalePrice'],axis=1)
Y=house_data['SalePrice']

X_train,X_test,Y_train,Y_test =train_test_split(
    X,Y, test_size=0.2,random_state=0
)

In [46]:
X_train.head()
X_test.head()
Y_test.head()

1728    180921.19589
2689    180921.19589
1151    149900.00000
2762    180921.19589
1180    250000.00000
Name: SalePrice, dtype: float64

In [47]:
# Train Linear Regression Model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [48]:
model.predict(X_test)

array([191650.15923449, 256694.21204008, 172701.86041706, 178271.40635751,
       206419.73613526, 197732.89101834, 122841.48375805, 157878.58934738,
       191291.77887932, 204804.03308353, 150243.64027563, 219384.08152954,
       175255.50575308, 146897.11420032, 199206.87801954, 140385.69033295,
       168183.44447516, 163859.73646194, 199489.97467243, 197189.64221706,
       196128.98519652, 133933.9044786 , 213384.66385958, 171491.85738482,
       134813.81633663, 155413.33744835, 147306.70226195, 172544.46498721,
       162993.16873967, 149133.18652125, 165985.90539426, 190830.5097074 ,
       163121.19310168, 194180.0272962 , 173858.91795552, 196437.34882538,
       141050.11569808, 164048.62478896, 170097.87353521, 168791.86980326,
       213867.76779934, 227566.00767484, 225968.6660771 , 141556.624312  ,
       200123.25857303, 221255.82922142, 219628.05092849, 112066.64524959,
       170881.54038786, 195695.22225926, 199297.32301991, 194250.64094596,
       125567.52706621, 153150.46411961, 197129.20194131, 152353.39846162,
       135830.20477894, 222158.33887991, 182830.5698671 , 199591.81857295,
       206995.28102922, 167071.63657689, 132145.03008326, 165280.23809106,
       191581.54045589, 193196.65980594, 103591.35181864, 152442.19956667,
       159762.6150873 , 178125.05210999, 161177.87763618, 202334.03218545,
       182622.91838593, 210320.34244288, 178795.69789939, 152790.32828779,
       196562.57185731, 188656.29977069, 108861.32389705, 205452.4118858 ,
       146418.04130528, 185508.0587886 , 200085.66470104, 173664.15115613,
       152563.57845667, 167130.72701882, 156085.4524303 , 205144.53831838,
       156262.27455351, 166136.79845492, 170341.99178056, 202329.07708251,
       178583.46245341, 154552.01748482, 182038.45296562, 140041.69857018,
       166159.47680367, 159380.2763784 , 180167.41246586, 130669.94938674,
       158226.58894704, 161846.4400881 , 183023.44636534, 197549.80792773,
       147124.96528779, 207299.5322997 , 200496.89994813, 203173.63119264,
       136094.1807554 , 189217.84564846, 125391.7640702 , 240341.69712077,
       189002.73523215, 203512.92334777, 195101.90539682, 182486.30719165,
       214773.27902033, 162974.20081412, 223397.43900139, 157571.78490549,
       249563.70910754, 236224.16581948, 188980.2377198 , 156848.38730683,
       164643.13017447, 212348.10352044, 179568.16162026, 183563.71858062,
       162040.75641553, 174208.90619856, 138164.41005465, 180053.61341677,
       219327.37215153, 183653.16593677, 142553.61307008, 159921.46618761,
       216942.14453575, 153915.58503432, 180529.34303608, 224214.08382836,
       140570.48811539, 184988.42070619, 189369.51151103, 184105.93719488,
       190463.08648835, 186086.66449492, 204289.1046177 , 173081.36360414,
       122388.9132208 , 153238.88277149, 206588.82104785, 193089.81627246,
       162612.70886649, 156210.93746847, 134697.88704496, 129352.58363822,
       152894.00465785, 134080.1714976 , 202690.2475415 , 195507.125394  ,
       163581.29424808, 143358.34582481, 194462.55540589, 163917.81143593,
       166293.10329643, 214040.98938066, 211574.68273739, 191924.47306021,
       218346.68932358, 192370.65283059, 191839.44884241, 140982.74331062,
       170986.91658595, 228467.4562873 , 189795.6682496 , 171380.98149268,
       167204.51996726, 195920.40314583, 222685.06032403, 211418.99874296,
       139003.19634302, 183425.22379166, 198388.68215031, 164097.59907819,
       207873.45493518, 212662.26482356, 193415.1317507 , 224259.2669964 ,
       124529.11386476, 183742.48459046, 162835.16412624, 150047.84524216,
       185121.53680951, 158437.3000156 , 165040.56655029, 215374.3944688 ,
       246793.49156565, 183091.87821116, 152634.0926372 , 145412.95138875,
       206240.84968935, 177877.83321642, 198176.94681376, 178169.10630309,
       171750.44278289, 151088.79987453, 186306.32479273, 206520.86513188,
       164877.50812911, 127726.22291576, 150686.4908136 , 181695.11905211,
       212179.86581805, 163103.3117167 , 152990.85121135, 180660.39432206,
       169464.79092851, 177441.17468368, 191677.84762687, 197762.89509113,
       140196.22437798, 165031.30577442, 163103.04822369, 160217.99067023,
       161630.69688485, 228686.06017948, 201734.49295909, 156776.61383724,
       220764.25844639, 172657.94975285, 157892.28566169, 130188.03823271,
       181890.96638082, 162193.22369803, 148362.85636308, 204032.69860388,
       140771.32914957, 197745.59464927, 202216.48472239, 154584.86958343,
       192980.24833891, 189433.1411219 , 163974.09038389, 128151.6150645 ,
       165471.78520811, 154009.44986317, 114276.38518659, 191467.14998444,
       201766.35991297, 243815.22636917, 197201.29612012, 167978.07836354,
       149593.04998125, 235215.01178877, 209517.57924124, 157168.11391901,
       200963.07577616, 224670.00232521, 199702.57758213, 196093.20891354,
       184286.00314886, 201678.13110549, 168866.40455299, 192032.40886444,
       228268.61200492, 167734.6271118 , 137099.84842232, 162448.66612708,
       214718.91834374, 125018.18748767, 109055.48638792, 228389.08792348,
       202622.64399624, 157986.45349265, 135999.369694  , 245970.18690599,
       249845.01775737, 169861.56360205, 187794.0844776 , 156985.37589436,
       157691.99793423, 189357.63616315, 202300.30906457, 208686.87567853,
       161557.81725842, 186342.19636852, 277953.80056097, 179682.44249769,
       217078.93371855, 178528.39054036, 141387.32550343, 209110.24994303,
       220006.04936558, 170166.16781381, 190120.3202604 , 157011.61608482,
       210385.07824687, 189335.83885029, 200391.76883881, 213929.83229419,
       162650.3261084 , 115283.60135912, 211925.01942293, 180839.69874967,
       291856.58431674, 184922.71917659, 150475.23714941, 217765.01443414,
       152525.73762179, 186884.12503032, 179577.14414357, 192476.57496545,
       151020.19175114, 217736.2017309 , 165335.87466962, 159383.85992065,
       196827.74066614, 164424.92883678, 242181.5109977 , 154617.6870826 ,
       194373.53999969, 135000.9787347 , 187072.03734777, 107214.63585346,
       206974.72943921, 197350.23444532, 208493.9902068 , 133273.95641863,
       194771.94291733, 164041.51012583, 159939.90216637, 266639.92753123,
       152297.95485236, 223931.9761604 , 222080.19837819, 168237.58249014,
       213650.31403729, 169815.08598668, 201238.18626997, 196477.95456759,
       190584.67394626, 125250.7313308 , 227968.25089577, 152567.07340142,
       160573.22978706, 163896.735831  , 153367.97438253, 136918.0768587 ,
       209967.01768203, 176282.38763741, 194370.01118432, 187669.6725847 ,
       225903.28599189, 133781.84545029, 200243.70888712, 177422.03343018,
       172989.17397812, 150838.46729042, 231289.43158382, 208124.109234  ,
       221275.57230877, 199603.37870735, 151767.01879376, 190894.97635623,
       143551.53699387, 217139.83814417, 226955.46289121, 203998.00543364,
       155633.01612875, 191633.40436021, 204342.6414237 , 192368.22665126,
       163754.02503987, 174021.77692558, 243706.08096336, 156725.04372106,
       167041.89355353, 214685.1748546 , 144895.55674015, 209313.62190061,
       163146.67410134, 161771.234087  , 154664.05356784, 171655.10772044,
       149555.18043941, 198174.06070772, 200111.90335823, 197824.25295636,
       205973.2032717 , 179052.87849809, 195206.82566327, 201548.27628393,
       214413.91267213, 217695.35791504, 198118.97722547, 145419.62391365,
       167661.80566762, 145150.32785699, 197843.67050141, 232420.83897517,
       228932.64661106, 181626.38293201, 197042.42000746, 214470.37558414,
       174353.19765831, 197535.49354661, 178689.43024093, 168069.84823825,
       174460.32028928, 161464.40422563, 234350.20175697, 201280.89094349,
       187522.91972751, 152371.90750043, 145640.66049918, 120263.66982781,
       211866.82664087, 160761.93890184, 163968.84110086, 168770.11405902,
       183747.1486932 , 176992.63466183, 153794.10854779, 184052.15279831,
       191768.51219328, 209682.65347589, 161125.30944926, 210090.50526249,
       215470.07799217, 153495.13973921, 165551.74492479, 202057.10277662,
       172184.48145825, 149617.58767225, 139929.10088473, 179284.78777547,
       198407.40550871, 165425.35995843, 128209.16659525, 135701.62307083,
       183420.46855715, 187025.80284937, 167474.70625204, 179196.37272046,
       139251.60413747, 227418.60176899, 171627.9853591 , 166289.5266619 ,
       186638.1712703 , 142600.94776956, 201580.93561705, 200192.44573651,
       170082.25003434, 194505.01077074, 145595.40180286, 195878.91633478,
       147861.29174848, 147329.06016296, 153318.39868591, 174818.0599693 ,
       183377.258809  , 199042.74360385, 219593.47355583, 206456.60283519,
       175016.14153767, 158821.3300455 , 219803.60803862, 269553.8320814 ,
       150766.9001694 , 153125.92510773, 185376.42081139, 226013.02441779,
       115570.66258354, 183639.92184373, 196954.95505775, 193627.39231337,
       259957.70057708, 149594.52708001, 189973.96724419, 183113.36610217,
       212063.08764871, 221204.93939473, 167845.22973508, 200958.19846304,
       246893.40917657, 231133.50981015, 171498.56904499, 153512.11119462,
       213751.01251444, 198547.49663447, 167935.69047257, 193154.04942848,
       134654.55719415, 196741.484049  , 185922.03902849, 227195.52318948,
       184001.77126075, 147933.82642163, 156857.28218923, 160645.84320328,
       158138.57932742, 187173.20783566,  97671.42341415, 218282.58035155,
       193387.77206031, 206188.30332298, 200846.96849105, 227789.25563364,
       123621.76197758, 197691.88284033, 209941.21451114, 200608.56266015,
       208310.58821439, 201973.02781632, 204370.92669916, 211452.39083897,
       178697.51245787, 129454.13330637, 199534.91725978, 174038.35075142,
       203429.3475993 , 214759.28854557, 201334.97059272, 150222.81481052,
       234092.68252893, 165717.80739965, 161344.5223729 , 192013.87587522,
       213751.70058395, 175590.51698924, 146271.83378554, 124017.02046821,
       205483.06711297, 175728.28244499, 182824.49818821, 216873.64501293,
       158830.29175726, 166528.17251335, 161526.26797488, 193569.76107649,
       152435.51796907, 191824.98161746, 203366.63090273, 178666.12586971,
       152510.99784763, 207219.01682496, 187658.02790857, 140361.7074512 ,
       189903.38566049, 194251.08026035, 146480.40764896, 175955.19708697,
       158995.89513212, 140331.28428198, 213327.09841872, 158318.58409243,
       176701.49361092, 191927.12971953, 169858.19288017, 224079.90237519,
       167074.16533938, 170130.51855399, 115775.0998438 , 221552.77665546,
       194319.56180773, 171600.61447218, 220920.5004128 , 204553.03927472,
       134709.72894318, 125301.90266126, 212075.44364219, 203524.73530383,
       173415.20564912, 213076.80929431, 180816.47116083, 202257.67850051,
       189445.30482476, 126858.84831436, 168536.34337095, 216034.91618086,
       157497.77526479, 226436.30256943, 178107.07759147])

In [52]:
#Model Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

y_pred=model.predict(X_test)

print("R2 Score: ",r2_score(Y_test,y_pred))
print("MAE: ",mean_absolute_error(Y_test,y_pred))
print("RMSE: ",np.sqrt(mean_squared_error(Y_test,y_pred)))
print(mean_absolute_percentage_error(Y_test,y_pred))

R2 Score:  0.37414217961384233
MAE:  30829.936664322064
RMSE:  41138.55870230141
0.1874202546342793

In [55]:
# feature scaling - to try and improve baseline performance
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

model=LinearRegression()
model.fit(X_train_scaled,Y_train)
y_pred=model.predict(X_test_scaled)

print("R2 Score: ",r2_score(Y_test,y_pred))
print("MAE: ",mean_absolute_error(Y_test,y_pred))
print("RMSE: ",np.sqrt(mean_squared_error(Y_test,y_pred)))
print(mean_absolute_percentage_error(Y_test,y_pred))

R2 Score:  0.37414217961385343
MAE:  30829.936664321856
RMSE:  41138.558702301045
0.18742025463427794

In [56]:
house_data

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
1,20,9600,8,1976,1976,0.0,1262.0,181500.00000,False,False,...,False,False,False,True,False,False,False,False,False,False
2,60,11250,5,2001,2002,0.0,920.0,223500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
3,70,9550,5,1915,1970,0.0,756.0,140000.00000,False,False,...,False,False,False,False,False,False,False,False,True,False
4,60,14260,5,2000,2000,0.0,1145.0,250000.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,1936,7,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2915,160,1894,5,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2916,20,20000,7,1960,1996,0.0,1224.0,180921.19589,False,False,...,False,False,False,False,False,False,False,True,False,False
2917,85,10441,5,1992,1992,0.0,912.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False
2918,60,9627,5,1993,1994,0.0,996.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False